services:
  - type: web
    name: erikas-homemade
    env: python
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: erikas-homemade-db
          property: connectionString
    buildCommand: ""
    startCommand: ""
