# Generated by Django 5.0.4 on 2024-07-21 22:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='producto_imgs/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_producto', models.CharField(max_length=1)),
                ('estado_catalogo', models.CharField(max_length=1)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_servicio', models.CharField(default='A', max_length=1)),
                ('estado_catalogo', models.CharField(default='A', max_length=1)),
                ('img', models.ImageField(upload_to='servicio_imgs/')),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipo_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('estado_producto', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'tipo_productos',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('idTipo_Servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipoServicio', models.CharField(max_length=50)),
                ('estado_tipoServicio', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'tipo_servicios',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_pedido', models.DateTimeField()),
                ('descripcion_pedido', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evidencia_pago', models.ImageField(upload_to='pedidos/')),
                ('estado_pedido', models.CharField(default='Por hacer', max_length=80)),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoServicio',
            fields=[
                ('idDetalle_Pedido_Servicio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_servicios', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_inicial_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.servicio')),
            ],
            options={
                'db_table': 'detalle_pedido_servicios',
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoProducto',
            fields=[
                ('idDetalle_Pedido_Productos', models.AutoField(primary_key=True, serialize=False)),
                ('cant_productos', models.IntegerField()),
                ('nombre_productos', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio_inicial_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_productos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto')),
            ],
            options={
                'db_table': 'detalle_pedido_productos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='pedidos.DetallePedidoProducto', to='pedidos.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicios',
            field=models.ManyToManyField(through='pedidos.DetallePedidoServicio', to='pedidos.servicio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_TipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.tipoproducto'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_TipoServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.tiposervicio'),
        ),
    ]
