# Generated by Django 5.0.4 on 2024-04-18 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipo_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('estado_producto', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'tipo_productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='producto_imgs/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_producto', models.CharField(max_length=1)),
                ('estado_catalogo', models.CharField(max_length=1)),
                ('cantidad', models.IntegerField()),
                ('id_TipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.tipoproducto')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
