# Generated by Django 5.0.4 on 2024-07-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado_catalogo',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1),
        ),
    ]
