# Generated by Django 5.0.4 on 2024-07-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_producto_estado_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado_catalogo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
