# Generated by Django 5.0.4 on 2024-04-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_detallepedidoservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado_catalogo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado_catalogo',
            field=models.BooleanField(default=False),
        ),
    ]
