# Generated by Django 5.0.4 on 2024-04-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_producto_estado_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='estado_tipoServicio',
            field=models.CharField(default='Por hacer', max_length=80),
        ),
    ]
