# Generated by Django 5.0.4 on 2024-04-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_tiposervicio_estado_tiposervicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(default='Por hacer', max_length=80),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='estado_producto',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='estado_tipoServicio',
            field=models.CharField(max_length=80),
        ),
    ]
