# Generated by Django 5.0.4 on 2024-04-24 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_pedido_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechaCreacion_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(),
        ),
    ]
