# Generated by Django 5.0.4 on 2024-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_pedido_evidencia_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='evidencia_pago',
            field=models.JSONField(blank=True, null=True, verbose_name='Evidencia de pago'),
        ),
    ]
