# Generated by Django 5.0.4 on 2024-05-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_pedido_evidencia_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='evidencia_pago',
            field=models.ImageField(upload_to='pedidos/'),
        ),
    ]
