# Generated by Django 5.0.4 on 2024-05-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_alter_pedido_evidencia_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado_catalogo',
            field=models.CharField(max_length=1),
        ),
    ]
