# Generated by Django 5.0.4 on 2024-05-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_alter_servicio_estado_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado_catalogo',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado_servicio',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
