# Generated by Django 5.0.4 on 2024-12-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_permiso', models.CharField(max_length=50)),
                ('estado_permiso', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
                ('estado_rol', models.CharField(default='A', max_length=1)),
                ('permisos', models.ManyToManyField(to='usuarios.permiso')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('documento', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=255)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('imagen', models.ImageField(default='user_images/iconosesion.jpg', upload_to='user_images/')),
                ('idRol', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
