# Generated by Django 5.0.4 on 2024-04-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolxpermiso',
            old_name='permiso',
            new_name='idPermiso',
        ),
        migrations.RenameField(
            model_name='rolxpermiso',
            old_name='rol',
            new_name='idRol',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='idRol',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=50),
        ),
    ]
