# Generated by Django 5.0.4 on 2024-04-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permiso',
            table='permiso',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.AlterModelTable(
            name='rolxpermiso',
            table='rolxpermiso',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
