# Generated by Django 5.0.4 on 2024-04-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_permiso_rolxpermiso_idpermiso_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permiso',
            table='permisos',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='rolxpermiso',
            table='rolxpermisos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
