# Generated by Django 5.0.4 on 2024-04-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_permiso_table_alter_rol_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permiso',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rol',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rolxpermiso',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
