# Generated by Django 5.0.4 on 2024-04-19 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_permiso_table_alter_rol_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idRol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.rol'),
        ),
    ]
