# Generated by Django 5.0.4 on 2024-04-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_idrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(to='usuarios.permiso'),
        ),
    ]
