# Generated by Django 5.0.4 on 2024-04-24 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_delete_rolxpermiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idRol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='usuarios.rol'),
        ),
    ]
