# Generated by Django 5.0.4 on 2024-04-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserva',
            table='reservas',
        ),
    ]
