# Generated by Django 5.0.4 on 2024-04-23 21:29

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateTimeField(validators=[reservas.models.validate_fecha_hoy]),
        ),
    ]
