# Generated by Django 5.0.4 on 2024-07-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
